### ISSUE TITLE
How are the training samples generated 

### ISSUE THREAD

**Issue by Melody-doudou** [sharif-apu/BJDD_CVPR21#9]
Hi! In the paper, you said that you extracted 741,968 non-overlapping image patches of dimension 128*128 from DIV2K and Flickr2K datasets. While in the code, when doing data sampling in the code ("python main.py -ds"), the 128*128 images are directly resized from original images of DIV2K dataset. I am wondering when you trained your model (which led to the released pretrained weights), which way did you use to generate the training samples. Thanks a lot!

**Comment by sharif-apu** [comment]
Please see lines 80-84 on https://github.com/sharif-apu/BJDD_CVPR21/blob/main/dataTools/processDataset.py for sampling process. You may use the file separately at your convenience. We extracted image patches with https://github.com/sharif-apu/BJDD_CVPR21/blob/main/dataTools/patchExtractor.py and applied sampled images according to the target CFA.

**Comment by Melody-doudou** [comment]
> Please see lines 80-84 on https://github.com/sharif-apu/BJDD_CVPR21/blob/main/dataTools/processDataset.py for sampling process. You may use the file separately at your convenience. We extracted image patches with https://github.com/sharif-apu/BJDD_CVPR21/blob/main/dataTools/patchExtractor.py and applied sampled images according to the target CFA.

I see. Thank you for the explanation!
